/**
 * Shadow Realm DLC — 카드 데이터 (37종)
 * Summon(10) / Augment(14) / Spell(13)
 * 테마: Shadow / Void / Death
 */

export const SHADOW_CARDS = [

  // ════════════════════════════════════════════════════
  // ── SUMMON (10) ───────────────────────────────────
  // ════════════════════════════════════════════════════
  {
    id: 'summon_void_sentinel',
    name: 'Void Sentinel',     nameKo: '공허 파수꾼',
    type: 'summon', rarity: 'rare', cost: 5, icon: '🌌',
    desc:   'Place a Void Sentinel. Very high damage, long range, slow attack. Ignores 25% of enemy defenses.',
    descKo: '공허 파수꾼을 배치합니다. 매우 높은 피해, 긴 사거리, 느린 공속. 적 방어력 25% 무시.',
    tower: 'void_sentinel', dlc: 'shadow_realm',
  },
  {
    id: 'summon_shadow_weaver',
    name: 'Shadow Weaver',     nameKo: '그림자 직조자',
    type: 'summon', rarity: 'uncommon', cost: 4, icon: '🕷️',
    desc:   'Place a Shadow Weaver. Fast attack, applies Shadow DoT (6 DPS for 3s) on each hit.',
    descKo: '그림자 직조자를 배치합니다. 빠른 공속, 명중 시 Shadow DoT 부여 (초당 6 피해, 3초).',
    tower: 'shadow_weaver', dlc: 'shadow_realm',
  },
  {
    id: 'summon_phantom_sniper',
    name: 'Phantom Sniper',    nameKo: '환영 저격수',
    type: 'summon', rarity: 'rare', cost: 5, icon: '👁️',
    desc:   'Place a Phantom Sniper. Extreme range, massive damage, very slow attack. Deals 2× damage to slowed enemies.',
    descKo: '환영 저격수를 배치합니다. 극도의 사거리, 대피해, 매우 느린 공속. 감속 적에게 2배 피해.',
    tower: 'phantom_sniper', dlc: 'shadow_realm',
  },
  {
    id: 'summon_void_sentinel_2',
    name: 'Void Obelisk',      nameKo: '공허 오벨리스크',
    type: 'summon', rarity: 'rare', cost: 5, icon: '🗿',
    desc:   'Place a Void Obelisk. Slow attack but passively slows all enemies in a large radius by 20%.',
    descKo: '공허 오벨리스크를 배치합니다. 느린 공속이지만 광역 범위 내 모든 적을 20% 지속 감속.',
    tower: 'void_sentinel', dlc: 'shadow_realm',
  },
  {
    id: 'summon_shadow_cannon',
    name: 'Shadow Cannon',     nameKo: '그림자 대포',
    type: 'summon', rarity: 'uncommon', cost: 3, icon: '🕳️',
    desc:   'Place a Shadow Cannon. Splash damage + applies Shadow DoT to every enemy in the blast.',
    descKo: '그림자 대포를 배치합니다. 범위 피해 + 폭발 내 모든 적에게 Shadow DoT 부여.',
    tower: 'bone_archer', dlc: 'shadow_realm',
  },
  {
    id: 'summon_specter',
    name: 'Specter',           nameKo: '유령',
    type: 'summon', rarity: 'common', cost: 2, icon: '👻',
    desc:   'Place a Specter tower. Very fast attack, moderate damage. Cheapest Shadow tower.',
    descKo: '유령 타워를 배치합니다. 매우 빠른 공속, 중간 피해. 가장 저렴한 그림자 타워.',
    tower: 'bone_archer', dlc: 'shadow_realm',
  },
  {
    id: 'summon_death_knight',
    name: 'Death Knight',      nameKo: '죽음의 기사',
    type: 'summon', rarity: 'uncommon', cost: 4, icon: '💀',
    desc:   'Place a Death Knight. High damage, short range, very fast reload. Ideal at chokepoints.',
    descKo: '죽음의 기사를 배치합니다. 높은 피해, 짧은 사거리, 매우 빠른 재장전. 목 지점에 최적.',
    tower: 'shadow_strike', dlc: 'shadow_realm',
  },
  {
    id: 'summon_void_mage',
    name: 'Void Mage',         nameKo: '공허 마법사',
    type: 'summon', rarity: 'rare', cost: 5, icon: '🌀',
    desc:   'Place a Void Mage. Slows enemies 35% and deals bonus damage equal to 4% of their current HP.',
    descKo: '공허 마법사를 배치합니다. 적을 35% 감속하고 현재 HP의 4%에 해당하는 추가 피해.',
    tower: 'shadow_weaver', dlc: 'shadow_realm',
  },
  {
    id: 'summon_bone_golem',
    name: 'Bone Golem',        nameKo: '뼈 골렘',
    type: 'summon', rarity: 'common', cost: 3, icon: '🦴',
    desc:   'Place a Bone Golem. Very high splash damage, extremely slow attack. Best in crowds.',
    descKo: '뼈 골렘을 배치합니다. 매우 높은 범위 피해, 극도로 느린 공속. 다수 적에게 최적.',
    tower: 'shadow_strike', dlc: 'shadow_realm',
  },
  {
    id: 'summon_phantom_archer',
    name: 'Phantom Archer',    nameKo: '환영 궁수',
    type: 'summon', rarity: 'uncommon', cost: 3, icon: '🏹',
    desc:   'Place a Phantom Archer. Moderate damage, fast attack. Shadow energy enhances every 5th shot.',
    descKo: '환영 궁수를 배치합니다. 중간 피해, 빠른 공속. 5번째 공격마다 그림자 에너지 강화.',
    tower: 'bone_archer', dlc: 'shadow_realm',
  },

  // ════════════════════════════════════════════════════
  // ── AUGMENT (14) ─────────────────────────────────
  // ════════════════════════════════════════════════════
  {
    id: 'aug_soul_rift',
    name: 'Soul Rift',         nameKo: '영혼 균열',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '💜',
    desc:   'Target tower gains +80% damage and +20% attack range.',
    descKo: '타워 피해 +80%, 사거리 +20%.',
    effect: { stats: [{ stat: 'damage', mult: 1.8 }, { stat: 'range', mult: 1.2 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_void_edge',
    name: 'Void Edge',         nameKo: '공허의 날',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '🌑',
    desc:   'Target tower gains +100% damage but loses 20% attack range. Massive burst at close range.',
    descKo: '타워 피해 +100%, 사거리 -20%. 근거리에서 폭발적인 화력.',
    effect: { stats: [{ stat: 'damage', mult: 2.0 }, { stat: 'range', mult: 0.8 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_shadow_surge',
    name: 'Shadow Surge',      nameKo: '그림자 파동',
    type: 'augment', rarity: 'common', cost: 2, icon: '🌒',
    desc:   'Target tower gains +50% damage and attacks 40% faster.',
    descKo: '타워 피해 +50%, 공격속도 40% 증가.',
    effect: { stats: [{ stat: 'damage', mult: 1.5 }, { stat: 'attackSpeed', mult: 0.6 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_phantom_step',
    name: 'Phantom Step',      nameKo: '환영의 발걸음',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '👣',
    desc:   'Target tower gains +35% attack range and attacks 35% faster.',
    descKo: '타워 사거리 +35%, 공격속도 35% 증가.',
    effect: { stats: [{ stat: 'range', mult: 1.35 }, { stat: 'attackSpeed', mult: 0.65 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_void_infusion',
    name: 'Void Infusion',     nameKo: '공허 주입',
    type: 'augment', rarity: 'rare', cost: 5, icon: '🔯',
    desc:   'Target tower gains +300% attack range. Covers the entire map. Best on high-damage towers.',
    descKo: '타워 사거리 +300%. 전체 맵 커버. 고피해 타워에 최적.',
    effect: { stat: 'range', mult: 4.0 },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_entropy_core',
    name: 'Entropy Core',      nameKo: '엔트로피 코어',
    type: 'augment', rarity: 'rare', cost: 4, icon: '♾️',
    desc:   'Target tower gains +80% damage and attacks 80% faster. Unstable but devastating.',
    descKo: '타워 피해 +80%, 공격속도 80% 증가. 불안정하지만 파괴적.',
    effect: { stats: [{ stat: 'damage', mult: 1.8 }, { stat: 'attackSpeed', mult: 0.2 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_soul_link',
    name: 'Soul Link',         nameKo: '영혼 연결',
    type: 'augment', rarity: 'common', cost: 2, icon: '🔗',
    desc:   'Target tower gains +40% damage and attacks 30% faster.',
    descKo: '타워 피해 +40%, 공격속도 30% 증가.',
    effect: { stats: [{ stat: 'damage', mult: 1.4 }, { stat: 'attackSpeed', mult: 0.7 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_shadow_aura',
    name: 'Shadow Aura',       nameKo: '그림자 오라',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '🌫️',
    desc:   'Target tower gains +55% damage and +40% attack range. Radiates shadow energy.',
    descKo: '타워 피해 +55%, 사거리 +40%. 그림자 에너지를 방사합니다.',
    effect: { stats: [{ stat: 'damage', mult: 1.55 }, { stat: 'range', mult: 1.4 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_phantom_mark',
    name: 'Phantom Mark',      nameKo: '환영의 낙인',
    type: 'augment', rarity: 'common', cost: 2, icon: '🔮',
    desc:   'Target tower gains +55% damage and attacks 35% faster.',
    descKo: '타워 피해 +55%, 공격속도 35% 증가.',
    effect: { stats: [{ stat: 'damage', mult: 1.55 }, { stat: 'attackSpeed', mult: 0.65 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_void_eye',
    name: 'Void Eye',          nameKo: '공허의 눈',
    type: 'augment', rarity: 'rare', cost: 4, icon: '👁️',
    desc:   'Target tower gains +120% damage. The void stares through every enemy.',
    descKo: '타워 피해 +120%. 공허가 모든 적을 꿰뚫어봅니다.',
    effect: { stat: 'damage', mult: 2.2 },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_shadow_speed',
    name: 'Shadow Speed',      nameKo: '그림자 속도',
    type: 'augment', rarity: 'common', cost: 2, icon: '💨',
    desc:   'Target tower attacks 60% faster. Move with the shadows.',
    descKo: '타워 공격속도 60% 증가. 그림자처럼 움직이세요.',
    effect: { stat: 'attackSpeed', mult: 0.4 },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_death_essence',
    name: 'Death Essence',     nameKo: '죽음의 정수',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '☠️',
    desc:   'Target tower gains +70% damage and +30% attack range.',
    descKo: '타워 피해 +70%, 사거리 +30%.',
    effect: { stats: [{ stat: 'damage', mult: 1.7 }, { stat: 'range', mult: 1.3 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_void_mastery',
    name: 'Void Mastery',      nameKo: '공허 지배',
    type: 'augment', rarity: 'rare', cost: 5, icon: '🌌',
    desc:   'Target tower gains +100% damage, +50% range, and attacks 50% faster. The ultimate void rune.',
    descKo: '타워 피해 +100%, 사거리 +50%, 공격속도 50% 증가. 최강의 공허 룬.',
    effect: { stats: [{ stat: 'damage', mult: 2.0 }, { stat: 'range', mult: 1.5 }, { stat: 'attackSpeed', mult: 0.5 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_soul_rend',
    name: 'Soul Rend',         nameKo: '영혼 찢기',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '💔',
    desc:   'Target tower gains +90% damage but loses 25% attack range. Devastating at close quarters.',
    descKo: '타워 피해 +90%, 사거리 -25%. 근거리에서 파괴적.',
    effect: { stats: [{ stat: 'damage', mult: 1.9 }, { stat: 'range', mult: 0.75 }] },
    dlc: 'shadow_realm',
  },

  // ════════════════════════════════════════════════════
  // ── SPELL (13) ────────────────────────────────────
  // ════════════════════════════════════════════════════
  {
    id: 'spell_darkness',
    name: 'Darkness',          nameKo: '어둠',
    type: 'spell', rarity: 'uncommon', cost: 3, icon: '🌑',
    desc:   'All enemies -40% speed and all towers +20% damage for 6 seconds.',
    descKo: '모든 적 이동속도 -40%, 모든 타워 피해 +20%, 6초 지속.',
    effect: { type: 'darkness', slowAmt: 0.4, dmgBoost: 0.2, duration: 6000 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_shadow_nova',
    name: 'Shadow Nova',       nameKo: '그림자 노바',
    type: 'spell', rarity: 'rare', cost: 5, icon: '💜',
    desc:   'Deal damage equal to 60% of each enemy\'s MISSING HP. Devastates wounded enemies.',
    descKo: '모든 적의 잃은 HP의 60%에 해당하는 피해. 부상 적에게 파괴적.',
    effect: { type: 'shadow_nova', pct: 0.6 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_void_pulse',
    name: 'Void Pulse',        nameKo: '공허 파동',
    type: 'spell', rarity: 'uncommon', cost: 3, icon: '🔵',
    desc:   'Push the 3 furthest enemies back 3 hex steps toward spawn.',
    descKo: '가장 앞선 적 3명을 스폰 지점 방향으로 3칸 밀어냅니다.',
    effect: { type: 'void_pulse', count: 3, steps: 3 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_soul_feast',
    name: 'Soul Feast',        nameKo: '영혼 향연',
    type: 'spell', rarity: 'rare', cost: 4, icon: '💀',
    desc:   'Instantly kill all enemies below 25% HP. Gain 3 gold per enemy killed.',
    descKo: 'HP 25% 미만 적을 즉사. 처치한 적 1마리당 골드 3 획득.',
    effect: { type: 'soul_feast', hpThreshold: 0.25, goldPerKill: 3 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_phantom_strike',
    name: 'Phantom Strike',    nameKo: '환영 강타',
    type: 'spell', rarity: 'common', cost: 2, icon: '👊',
    desc:   'Deal 80 damage to 3 random enemies.',
    descKo: '무작위 적 3명에게 80 피해.',
    effect: { type: 'damage_random', count: 3, amount: 80 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_void_collapse',
    name: 'Void Collapse',     nameKo: '공허 붕괴',
    type: 'spell', rarity: 'uncommon', cost: 3, icon: '🕳️',
    desc:   'Slow all enemies 65% for 8 seconds. The void swallows their speed.',
    descKo: '모든 적을 8초 동안 65% 감속. 공허가 속도를 삼킵니다.',
    effect: { type: 'slow_all', amount: 0.65, duration: 8000 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_soul_surge',
    name: 'Soul Surge',        nameKo: '영혼 파동',
    type: 'spell', rarity: 'uncommon', cost: 2, icon: '⚡',
    desc:   'All towers deal +60% damage for 5 seconds.',
    descKo: '모든 타워 피해 +60%, 5초 지속.',
    effect: { type: 'damage_boost_all', mult: 1.6, duration: 5000 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_abyssal_wave',
    name: 'Abyssal Wave',      nameKo: '심연의 파도',
    type: 'spell', rarity: 'rare', cost: 5, icon: '🌊',
    desc:   'Deal 50 damage to all enemies and slow them 30% for 4 seconds.',
    descKo: '모든 적에게 50 피해 및 4초 동안 30% 감속.',
    effect: { type: 'nova', damage: 50, slowAmt: 0.3, slowDuration: 4000 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_shadow_step',
    name: 'Shadow Step',       nameKo: '그림자 발걸음',
    type: 'spell', rarity: 'uncommon', cost: 3, icon: '🌀',
    desc:   'Teleport the 5 furthest enemies back to the spawn point.',
    descKo: '가장 앞선 적 5명을 스폰 지점으로 순간이동합니다.',
    effect: { type: 'teleport_all', count: 5 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_death_toll',
    name: 'Death Toll',        nameKo: '죽음의 값',
    type: 'spell', rarity: 'common', cost: 1, icon: '🔔',
    desc:   'Gain 1 gold for each enemy killed so far this wave.',
    descKo: '이번 웨이브에서 처치한 적 1마리당 골드 1 획득.',
    effect: { type: 'gold_per_wave_kill' },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_entropy_cascade',
    name: 'Entropy Cascade',   nameKo: '엔트로피 연쇄',
    type: 'spell', rarity: 'rare', cost: 4, icon: '🌪️',
    desc:   'Deal 50% of each enemy\'s current HP as damage. The more HP they have, the more they suffer.',
    descKo: '모든 적의 현재 HP 50%에 해당하는 피해. HP가 많을수록 더 큰 피해.',
    effect: { type: 'percent_hp_damage', percent: 0.5 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_shadow_mend_2',
    name: 'Shadow Restoration', nameKo: '그림자 복원',
    type: 'spell', rarity: 'common', cost: 2, icon: '🖤',
    desc:   'Restore 1 Nexus HP. If already full, deal 30 damage to all enemies instead.',
    descKo: '넥서스 HP 1 회복. 이미 최대치라면 모든 적에게 30 피해.',
    effect: { type: 'heal_nexus', amount: 1, goldOnFull: 0, altEffect: 'damage_all_30' },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_void_grasp',
    name: 'Void Grasp',        nameKo: '공허의 손길',
    type: 'spell', rarity: 'common', cost: 2, icon: '🤚',
    desc:   'Freeze all enemies for 3 seconds. The void holds them in place.',
    descKo: '모든 적을 3초 동안 빙결합니다. 공허가 그들을 붙잡습니다.',
    effect: { type: 'freeze', duration: 3000 },
    dlc: 'shadow_realm',
  },
];
